version: '3'

services:
  db:
    container_name: taskmanager_db
    hostname: db.taskmanager.com
    image: postgres:14.2
    environment:
      POSTGRES_USER: "taskmanager"
      POSTGRES_PASSWORD: "task@manager2022"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
    networks:
      - taskmanager

  pgadmin:
    container_name: taskmanager_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    networks:
      - taskmanager
    volumes:
      - ./Docker/pgadmin/servers.json:/pgadmin4/servers.json 


networks: 
  taskmanager:
    driver: bridge