version: '3'

services:
  db:
    container_name: taskmanager_pg
    hostname: pg.taskmanager.com
    image: postgres:14.2
    environment:
      PGUSER: "taskmanager" #Variável pré-definir o usuário da ferramenta psql.
      POSTGRES_USER: "taskmanager"
      POSTGRES_PASSWORD: "task@manager2022"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
    networks:
      - taskmanager

  pgadmin:
    container_name: taskmanager_pgadmin
    hostname: pgadmin.taskmanager.com
    image: dpage/pgadmin4:6.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@taskmanager.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    networks:
      - taskmanager
    volumes:
      - ./Docker/pgadmin/servers.json:/pgadmin4/servers.json 

  ftp:
    container_name: taskmanager_ftp
    hostname: ftp.taskmanager.com
    image: stilliard/pure-ftpd:hardened
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: "taskmanager"
      FTP_USER_PASS: "@Ftp4tm"
      FTP_USER_HOME: "/home/taskmanager"
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./ftp:/home/taskmanager/
    networks:
      - taskmanager

  redis:
    container_name: taskmanager_redis
    hostname: redis.taskmanager.com
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass taskmanager #A senha será taskmanager
    ports:
      - "6379:6379"
    volumes:
      - $PWD/Docker/redis:/usr/local/etc/redis/redis.conf
    networks:
      - taskmanager

  api:
    container_name: taskmanager_api
    hostname: api.taskmanager.com
    image: taskmanager_api:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - taskmanager
    depends_on:
      - db

networks: 
  taskmanager:
    driver: bridge