spring:
    datasource:
        url: jdbc:postgresql://pg.taskmanager.com:5432/taskmanager
        username: taskmanager
        password: task@manager2022
           
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: false
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
                
    devtools:
        remote:
            secret: 123