spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/taskmanager
        username: taskmanager
        password: task@manager2022
           
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: false
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
                
    devtools:
        add-properties: false

    redis:
        host: localhost
        port: 6379
        password: taskmanager